redirects:  
    kit-accessibilite: gerer-sa-startup-detat-ou-de-territoires-au-quotidien/jameliore-le-design-et-lexperience-utilisateur/accessibilite-et-rgaa/kit-accessibilite/README.md
    check-accessibilite: gerer-sa-startup-detat-ou-de-territoires-au-quotidien/jameliore-le-design-et-lexperience-utilisateur/accessibilite-et-rgaa/formation-a-laccessibilite/10-choses-faciles-a-verifier-pour-un-site-plus-accessible.md
    welcome: travailler-a-beta-gouv/bienvenue/README.md
    welcome-dev: travailler-a-beta-gouv/bienvenue/embarquement-dev.md
    standards: gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-fais-des-choix-technologique/standards-de-qualite-beta.gouv.fr.md
    rgpd: gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-securise-mon-produit/guide-rgpd-et-securite.md
    formation: travailler-a-beta-gouv/se-former/les-formations-a-venir.md
    dashlord: travailler-a-beta-gouv/jutilise-les-outils-de-la-communaute/dashlord/README.md
    dsfr: gerer-sa-startup-detat-ou-de-territoires-au-quotidien/jameliore-le-design-et-lexperience-utilisateur/design-system-etat/README.md
    
